version: '3.3'

services:
  web:
    # image: lang:tag
    build: .
    command: /bin/bash -c "
            python3 manage.py migrate
            && python3 manage.py runserver 0.0.0.0:8000
            && pip install -r requirements.txt"
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    networks:
      - langunity

networks:
  langunity:
